version: "3.8"
services:
  hashcrack:
    build: .
    image: edu/hashcrack:latest
    command: ["web", "--addr", ":8080"]
    working_dir: /data
    volumes:
      - .:/data
      - uploads-data:/data/uploads
    ports:
      - "8080:8080"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

volumes:
  uploads-data:
